SacredMountain_3F_MapScripts::
	.byte 0


SacredMountain_3F_EventScript_Grunt1::
# 4 "data/maps/SacredMountain_3F/scripts.pory"
	trainerbattle_single TRAINER_ROCKET_GRUNT_SM_3F_1, SacredMountain_3F_Text_Grunt1_Intro, SacredMountain_3F_Text_Grunt1_Defeat
# 5 "data/maps/SacredMountain_3F/scripts.pory"
	msgbox SacredMountain_3F_Text_Grunt1_PostBattle, MSGBOX_AUTOCLOSE
	return


SacredMountain_3F_EventScript_Grunt2::
# 9 "data/maps/SacredMountain_3F/scripts.pory"
	trainerbattle_single TRAINER_ROCKET_GRUNT_SM_3F_2, SacredMountain_3F_Text_Grunt2_Intro, SacredMountain_3F_Text_Grunt2_Defeat
# 10 "data/maps/SacredMountain_3F/scripts.pory"
	msgbox SacredMountain_3F_Text_Grunt2_PostBattle, MSGBOX_AUTOCLOSE
	return


SacredMountain_3F_EventScript_Grunt3::
# 14 "data/maps/SacredMountain_3F/scripts.pory"
	trainerbattle_single TRAINER_ROCKET_GRUNT_SM_3F_3, SacredMountain_3F_Text_Grunt3_Intro, SacredMountain_3F_Text_Grunt3_Defeat
# 15 "data/maps/SacredMountain_3F/scripts.pory"
	msgbox SacredMountain_3F_Text_Grunt3_PostBattle, MSGBOX_AUTOCLOSE
	return


SacredMountain_3F_EventScript_Grunt4::
# 19 "data/maps/SacredMountain_3F/scripts.pory"
	trainerbattle_single TRAINER_ROCKET_GRUNT_SM_3F_4, SacredMountain_3F_Text_Grunt4_Intro, SacredMountain_3F_Text_Grunt4_Defeat
# 20 "data/maps/SacredMountain_3F/scripts.pory"
	msgbox SacredMountain_3F_Text_Grunt4_PostBattle, MSGBOX_AUTOCLOSE
	return


SacredMountain_3F_Text_Grunt1_Intro::
# 23 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Intro$"

SacredMountain_3F_Text_Grunt1_Defeat::
# 27 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Defeat$"

SacredMountain_3F_Text_Grunt1_PostBattle::
# 31 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Post$"

SacredMountain_3F_Text_Grunt2_Intro::
# 35 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Intro$"

SacredMountain_3F_Text_Grunt2_Defeat::
# 39 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Defeat$"

SacredMountain_3F_Text_Grunt2_PostBattle::
# 43 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Post$"

SacredMountain_3F_Text_Grunt3_Intro::
# 47 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Intro$"

SacredMountain_3F_Text_Grunt3_Defeat::
# 51 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Defeat$"

SacredMountain_3F_Text_Grunt3_PostBattle::
# 55 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Post$"

SacredMountain_3F_Text_Grunt4_Intro::
# 59 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Intro$"

SacredMountain_3F_Text_Grunt4_Defeat::
# 63 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Defeat$"

SacredMountain_3F_Text_Grunt4_PostBattle::
# 67 "data/maps/SacredMountain_3F/scripts.pory"
	.string "Post$"
