SacredIslandEast_MapScripts::
	.byte 0


SacredIslandEast_EventScript_BattleGirl1::
# 4 "data/maps/SacredIslandEast/scripts.pory"
	trainerbattle_single TRAINER_BATTLE_GIRL_SI_EAST_1, SacredIslandEast_Text_BattleGirl1_Intro, SacredIslandEast_Text_BattleGirl1_Defeat
# 5 "data/maps/SacredIslandEast/scripts.pory"
	msgbox SacredIslandEast_Text_BattleGirl1_PostBattle, MSGBOX_AUTOCLOSE
	return


SacredIslandEast_EventScript_Fischerman1::
# 9 "data/maps/SacredIslandEast/scripts.pory"
	trainerbattle_single TRAINER_FISHERMAN_SI_EAST_1, SacredIslandEast_Text_Fischerman1_Intro, SacredIslandEast_Text_Fischerman1_Defeat
# 10 "data/maps/SacredIslandEast/scripts.pory"
	msgbox SacredIslandEast_Text_Fischerman1_PostBattle, MSGBOX_AUTOCLOSE
	return


SacredIslandEast_EventScript_Picnicker1::
# 14 "data/maps/SacredIslandEast/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_SI_EAST_1, SacredIslandEast_Text_Picnicker1_Intro, SacredIslandEast_Text_Picnicker1_Defeat
# 15 "data/maps/SacredIslandEast/scripts.pory"
	msgbox SacredIslandEast_Text_Picnicker1_PostBattle, MSGBOX_AUTOCLOSE
	return


SacredIslandEast_EventScript_BirdKeeper1::
# 19 "data/maps/SacredIslandEast/scripts.pory"
	trainerbattle_single TRAINER_BIRD_KEEPER_SI_EAST_1, SacredIslandEast_Text_BirdKeeper1_Intro, SacredIslandEast_Text_BirdKeeper1_Defeat
# 20 "data/maps/SacredIslandEast/scripts.pory"
	msgbox SacredIslandEast_Text_BirdKeeper1_PostBattle, MSGBOX_AUTOCLOSE
	return


SacredIslandEast_EventScript_Lady1::
# 24 "data/maps/SacredIslandEast/scripts.pory"
	trainerbattle_single TRAINER_LADY_SI_EAST_1, SacredIslandEast_Text_Lady1_Intro, SacredIslandEast_Text_Lady1_Defeat
# 25 "data/maps/SacredIslandEast/scripts.pory"
	msgbox SacredIslandEast_Text_Lady1_PostBattle, MSGBOX_AUTOCLOSE
	return


SacredIslandEast_Text_BattleGirl1_Intro::
# 28 "data/maps/SacredIslandEast/scripts.pory"
	.string "Intro$"

SacredIslandEast_Text_BattleGirl1_Defeat::
# 32 "data/maps/SacredIslandEast/scripts.pory"
	.string "Defeat$"

SacredIslandEast_Text_BattleGirl1_PostBattle::
# 36 "data/maps/SacredIslandEast/scripts.pory"
	.string "Post$"

SacredIslandEast_Text_Fischerman1_Intro::
# 40 "data/maps/SacredIslandEast/scripts.pory"
	.string "Intro$"

SacredIslandEast_Text_Fischerman1_Defeat::
# 44 "data/maps/SacredIslandEast/scripts.pory"
	.string "Defeat$"

SacredIslandEast_Text_Fischerman1_PostBattle::
# 48 "data/maps/SacredIslandEast/scripts.pory"
	.string "Post$"

SacredIslandEast_Text_Picnicker1_Intro::
# 52 "data/maps/SacredIslandEast/scripts.pory"
	.string "Intro$"

SacredIslandEast_Text_Picnicker1_Defeat::
# 56 "data/maps/SacredIslandEast/scripts.pory"
	.string "Defeat$"

SacredIslandEast_Text_Picnicker1_PostBattle::
# 60 "data/maps/SacredIslandEast/scripts.pory"
	.string "Post$"

SacredIslandEast_Text_BirdKeeper1_Intro::
# 64 "data/maps/SacredIslandEast/scripts.pory"
	.string "Intro$"

SacredIslandEast_Text_BirdKeeper1_Defeat::
# 68 "data/maps/SacredIslandEast/scripts.pory"
	.string "Defeat$"

SacredIslandEast_Text_BirdKeeper1_PostBattle::
# 72 "data/maps/SacredIslandEast/scripts.pory"
	.string "Post$"

SacredIslandEast_Text_Lady1_Intro::
# 76 "data/maps/SacredIslandEast/scripts.pory"
	.string "Intro$"

SacredIslandEast_Text_Lady1_Defeat::
# 80 "data/maps/SacredIslandEast/scripts.pory"
	.string "Defeat$"

SacredIslandEast_Text_Lady1_PostBattle::
# 84 "data/maps/SacredIslandEast/scripts.pory"
	.string "Post$"
