MagmaCave_1F_MapScripts::
	.byte 0


MagmaCave_1F_EventScript_Grunt1::
# 4 "data/maps/MagmaCave_1F/scripts.pory"
	trainerbattle_single TRAINER_MAGMA_GRUNT_MAGMACAVE_1F_1, MagmaCave_1F_Text_Grunt1_Intro, MagmaCave_1F_Text_Grunt1_Defeat
# 5 "data/maps/MagmaCave_1F/scripts.pory"
	msgbox MagmaCave_1F_Text_Grunt1_PostBattle, MSGBOX_AUTOCLOSE
	return


MagmaCave_1F_EventScript_Grunt2::
# 9 "data/maps/MagmaCave_1F/scripts.pory"
	trainerbattle_single TRAINER_MAGMA_GRUNT_MAGMACAVE_1F_2, MagmaCave_1F_Text_Grunt2_Intro, MagmaCave_1F_Text_Grunt2_Defeat
# 10 "data/maps/MagmaCave_1F/scripts.pory"
	msgbox MagmaCave_1F_Text_Grunt2_PostBattle, MSGBOX_AUTOCLOSE
	return


MagmaCave_1F_EventScript_Grunt3::
# 14 "data/maps/MagmaCave_1F/scripts.pory"
	trainerbattle_single TRAINER_MAGMA_GRUNT_MAGMACAVE_1F_3, MagmaCave_1F_Text_Grunt3_Intro, MagmaCave_1F_Text_Grunt3_Defeat
# 15 "data/maps/MagmaCave_1F/scripts.pory"
	msgbox MagmaCave_1F_Text_Grunt3_PostBattle, MSGBOX_AUTOCLOSE
	return


MagmaCave_1F_EventScript_Grunt4::
# 19 "data/maps/MagmaCave_1F/scripts.pory"
	trainerbattle_single TRAINER_MAGMA_GRUNT_MAGMACAVE_1F_4, MagmaCave_1F_Text_Grunt4_Intro, MagmaCave_1F_Text_Grunt4_Defeat
# 20 "data/maps/MagmaCave_1F/scripts.pory"
	msgbox MagmaCave_1F_Text_Grunt4_PostBattle, MSGBOX_AUTOCLOSE
	return


MagmaCave_1F_EventScript_Grunt5::
# 24 "data/maps/MagmaCave_1F/scripts.pory"
	trainerbattle_single TRAINER_MAGMA_GRUNT_MAGMACAVE_1F_5, MagmaCave_1F_Text_Grunt5_Intro, MagmaCave_1F_Text_Grunt5_Defeat
# 25 "data/maps/MagmaCave_1F/scripts.pory"
	msgbox MagmaCave_1F_Text_Grunt5_PostBattle, MSGBOX_AUTOCLOSE
	return


MagmaCave_1F_Text_Grunt1_Intro::
# 28 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Intro$"

MagmaCave_1F_Text_Grunt1_Defeat::
# 32 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Defeat$"

MagmaCave_1F_Text_Grunt1_PostBattle::
# 36 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Post$"

MagmaCave_1F_Text_Grunt2_Intro::
# 40 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Intro$"

MagmaCave_1F_Text_Grunt2_Defeat::
# 44 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Defeat$"

MagmaCave_1F_Text_Grunt2_PostBattle::
# 48 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Post$"

MagmaCave_1F_Text_Grunt3_Intro::
# 52 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Intro$"

MagmaCave_1F_Text_Grunt3_Defeat::
# 56 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Defeat$"

MagmaCave_1F_Text_Grunt3_PostBattle::
# 60 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Post$"

MagmaCave_1F_Text_Grunt4_Intro::
# 64 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Intro$"

MagmaCave_1F_Text_Grunt4_Defeat::
# 68 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Defeat$"

MagmaCave_1F_Text_Grunt4_PostBattle::
# 72 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Post$"

MagmaCave_1F_Text_Grunt5_Intro::
# 76 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Intro$"

MagmaCave_1F_Text_Grunt5_Defeat::
# 80 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Defeat$"

MagmaCave_1F_Text_Grunt5_PostBattle::
# 84 "data/maps/MagmaCave_1F/scripts.pory"
	.string "Post$"
