# 1 "data/maps/NightshadeOutskirtsHorror/scripts.pory"

# 2 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
NightshadeOutskirtsHorror_MapScripts::
# 3 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	.byte 0
# 4 "data/maps/NightshadeOutskirtsHorror/scripts.pory"

# 5 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
OutskirtsHorror_Script_Greg_House_Sign::
# 6 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	msgbox OutskirtsHorror_Greg_House_Sign, MSGBOX_SIGN
# 7 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	end
# 8 "data/maps/NightshadeOutskirtsHorror/scripts.pory"

# 9 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
OutskirtsHorror_Script_Greg_House_Closed::
# 10 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	msgbox OutskirtsHorror_Greg_House_Closed_Sign, MSGBOX_AUTOCLOSE
# 11 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	end
# 12 "data/maps/NightshadeOutskirtsHorror/scripts.pory"

# 13 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
OutskirtsHorror_Greg_House_Sign:
# 14 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	.string "Greg's House\n"
# 15 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	.string "Team Lead of Mining Operations$"
# 16 "data/maps/NightshadeOutskirtsHorror/scripts.pory"

# 17 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
OutskirtsHorror_Greg_House_Closed_Sign:
# 18 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	.string "The door is locked.\p"
# 19 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	.string "It appears like the owner\n"
# 20 "data/maps/NightshadeOutskirtsHorror/scripts.pory"
	.string "abandoned the building.$"
