# 1 "data/maps/NightmareCavernF1/scripts.pory"

# 2 "data/maps/NightmareCavernF1/scripts.pory"
NightmareCavernF1_MapScripts::
# 3 "data/maps/NightmareCavernF1/scripts.pory"
	.byte 0
# 4 "data/maps/NightmareCavernF1/scripts.pory"

# 5 "data/maps/NightmareCavernF1/scripts.pory"
NightmareCavernF1_Event_Ancient_Text::
# 6 "data/maps/NightmareCavernF1/scripts.pory"
	msgbox NightmareCavernF1_Ancient_Text, MSGBOX_SIGN
# 7 "data/maps/NightmareCavernF1/scripts.pory"
	end
# 8 "data/maps/NightmareCavernF1/scripts.pory"

# 9 "data/maps/NightmareCavernF1/scripts.pory"
NightmareCavernF1_Ancient_Text::
# 10 "data/maps/NightmareCavernF1/scripts.pory"
	.string "Cling to the neverending wakeness.\n"
# 11 "data/maps/NightmareCavernF1/scripts.pory"
	.string "Stay clear of the haunting dreams.\p"
# 12 "data/maps/NightmareCavernF1/scripts.pory"
	.string "Divided we enforce madness\n"
# 13 "data/maps/NightmareCavernF1/scripts.pory"
	.string "United we strip the seams.$"
