# 1 "data/maps/NightmareCavernF2/scripts.pory"

# 2 "data/maps/NightmareCavernF2/scripts.pory"
NightmareCavernF2_MapScripts::
# 3 "data/maps/NightmareCavernF2/scripts.pory"
	.byte 0
# 4 "data/maps/NightmareCavernF2/scripts.pory"

# 5 "data/maps/NightmareCavernF2/scripts.pory"
NightmareCavernF2_Event_Ancient_Text::
# 6 "data/maps/NightmareCavernF2/scripts.pory"
	msgbox NightmareCavernF2_Ancient_Text, MSGBOX_SIGN
# 7 "data/maps/NightmareCavernF2/scripts.pory"
	end
# 8 "data/maps/NightmareCavernF2/scripts.pory"

# 9 "data/maps/NightmareCavernF2/scripts.pory"
NightmareCavernF2_Event_Sign_Text::
# 10 "data/maps/NightmareCavernF2/scripts.pory"
	msgbox NightmareCavernF2_Sign_Text, MSGBOX_SIGN
# 11 "data/maps/NightmareCavernF2/scripts.pory"
	end
# 12 "data/maps/NightmareCavernF2/scripts.pory"

# 13 "data/maps/NightmareCavernF2/scripts.pory"
NightmareCavernF2_Ancient_Text::
# 14 "data/maps/NightmareCavernF2/scripts.pory"
	.string "“Protectorate of our Gods”\n"
# 15 "data/maps/NightmareCavernF2/scripts.pory"
	.string "Shelter to the weak.$"
# 16 "data/maps/NightmareCavernF2/scripts.pory"

# 17 "data/maps/NightmareCavernF2/scripts.pory"
NightmareCavernF2_Sign_Text::
# 18 "data/maps/NightmareCavernF2/scripts.pory"
	.string "“Sacred Hideout”\n"
# 19 "data/maps/NightmareCavernF2/scripts.pory"
	.string "Do not litter or disturb the wildlife.$"
