# 1 "data/maps/NightmareCavern/scripts.pory"

# 2 "data/maps/NightmareCavern/scripts.pory"
NightmareCavern_MapScripts::
# 3 "data/maps/NightmareCavern/scripts.pory"
	.byte 0
# 4 "data/maps/NightmareCavern/scripts.pory"

# 5 "data/maps/NightmareCavern/scripts.pory"
NightmareCavern_Event_Ancient_Text::
# 6 "data/maps/NightmareCavern/scripts.pory"
	msgbox NightmareCavern_Ancient_Text, MSGBOX_SIGN
# 7 "data/maps/NightmareCavern/scripts.pory"
	end
# 8 "data/maps/NightmareCavern/scripts.pory"

# 9 "data/maps/NightmareCavern/scripts.pory"
NightmareCavern_Ancient_Text::
# 10 "data/maps/NightmareCavern/scripts.pory"
	.string "There is a pretty unreadable message\n"
# 11 "data/maps/NightmareCavern/scripts.pory"
	.string "carved into the wall. It states:\p"
# 12 "data/maps/NightmareCavern/scripts.pory"
	.string "We are... ...prot... ...cave.\n"
# 13 "data/maps/NightmareCavern/scripts.pory"
	.string "Dark...ss shall hi... ...ence.\p"
# 14 "data/maps/NightmareCavern/scripts.pory"
	.string "...ry of... ...dreams\n"
# 15 "data/maps/NightmareCavern/scripts.pory"
	.string "...haunt... ...th.$"
